# Generated by Django 2.2.7 on 2019-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=60)),
                ('Pertanyaan', models.TextField()),
                ('level', models.CharField(choices=[('T', 'Tinggi'), ('S', 'Sedang'), ('R', 'Rendah')], max_length=1)),
            ],
        ),
    ]
