# Generated by Django 2.2.7 on 2019-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pertanyaan',
        ),
    ]
